require 'cucumber/rake/task'

task :unit_test => [:compile] do
  puts "Perform Unit Test"
end

task :integration_test => [:unit_test] do
  puts "Perform Integration Test"
end

task :compile do
  puts "Clean up previous compilation"
  puts "Perform compiling source code"
end

task :package => [:unit_test, :integration_test, :acceptance_test] do
  puts "Generate final TestApp.app package"
end

Cucumber::Rake::Task.new(task_name = "appium_test_ci", desc = "Run End to End automation suite") do |t|
  t.cucumber_opts = "--tags ~@ci --format pretty ./features/."
end

Cucumber::Rake::Task.new(task_name = "appium_test_sauce", desc = "Run End to End automation suite") do |t|
  t.cucumber_opts = "--tags ~@sauce --format pretty ./features/."
end


task :acceptance_test_ci => [:unit_test, :integration_test] do
  puts "Perform user acceptance test"
  Rake::Task["appium_test_ci"].invoke
end

task :acceptance_test_sauce => [:unit_test, :integration_test] do
	puts "Perform user acceptance test on saucelab"
	Rake::Task['appium_test_sauce'].invoke
end