# this is travis file

language: objective-c
cache: bundler

before_install:
- export NODEJS_VERSION=v4.4.3
- export NVM_DIR=$HOME/.nvm
- export PATH=$PATH:$NVM_DIR/$NODEJS_VERSION/bin
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
- source ~/.nvm/nvm.sh
- uname -a
- nvm install $NODEJS_VERSION
- nvm use $NODEJS_VERSION
- npm install -g appium
- npm install wd
- cd examples/ruby_acceptance_test

install:
- bundle install

script:
- rake acceptance_test