# this is travis file, which acts as a terminal on ci

language: objective-c
cache: bundler

before_install:
- export NODEJS_VERSION=v4.4.3
- export NVM_DIR=$HOME/.nvm
- export PATH=$PATH:$NVM_DIR/$NODEJS_VERSION/bin
# install nvm
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
# activate nvm
- source ~/.nvm/nvm.sh
- uname -a
- nvm install $NODEJS_VERSION
- nvm use $NODEJS_VERSION
- npm install -g appium
- npm install wd
- cd examples/ruby_acceptance_test

install:
- bundle install

script:
- rake acceptance_test

addons:
  sauce_connect:
    username: "nhung_nguyen"
    access_key: "vss8I3wHfmcYpKtAO+LEaZlMkjORdddZVnuiMuVa63so/K4y7PMzW/uFDchkIZ0bUdzG9hN1WhWpDb5QP4PhJU2ZT+JCtr5kio74ff1Jh4IApoq3kPCJwd/ET/RO8DDjJNSosE+nKpFjd0Ks8YxpH8Wdo9+c8XNnufGV8j/HDeOidChTSQZUK8/S5JmQHTjcs4SPcT9UJAiR9woO+Ej5AM0OnhD6TBssl46tcilB9/ASV3x41t3yEVGSlHjcv1z27WZXu76pK6tuiEdWadcsY1lYGVtrVdFLSRdYOuWW74vHnu9grFBjZMX5W8MaXSQGa2Akuz9pOsFLEwdRjD0Kp0p2YSxDIY5TqpypJJNXlb3mbvUu3Wsf1UlwBMmykAnCAlQusrq//8ix2T/rmcM/OxGzvI49I1urc54D4miBJPk6yTve6X6wZH1qlFaPMuMAcDVg3UgfvRuYFYPbgcQVi9qbsgXWsrFNxMOSw29/78KGvDLeBls7j10xJSP9bxIy40Vnz586KNspDfirgSz5aPWjm8AGViFZq0AHw3clj+p5gtt5yLkYKyTtla6D+uTzYZ6+WrEKuVzfv5TE0pHVvyzOxbB8/rwWwAuf5qUr43ywYHsFDTM8Zn4I5bkv61tAtoUnnUT12rvi2iCzHMQ86aoUEhvVMoJhAvkYAdKgNFQ="

script:
- rake acceptance_test    