language: objective-c
cache: bundler
before_install:
- export NODEJS_VERSION=v4.4.3
- export NVM_DIR=$HOME/.nvm
- export PATH=$PATH:$NVM_DIR/$NODEJS_VERSION/bin
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
- source ~/.nvm/nvm.sh
- uname -a
- nvm install $NODEJS_VERSION
- nvm use $NODEJS_VERSION
- npm install -g appium
- npm install wd
- cd examples/ruby_acceptance_test
- source ~/.bash_profile

install:
- bundle install
script:
- rake appium_test_ci

# zip TestApp.app file after every build, ideally if the test passes
# - rm ./apps/TestApp/build/release-iphonesimulator/TestApp.zip
- zip -r ./apps/TestApp/build/release-iphonesimulator/TestApp.zip ./apps/TestApp/build/release-iphonesimulator/TestApp.app
# upload the zip file to dropbox

# addons:
#   sauce_connect:
#     username: nhung_nguyen
# env:
#   global:
#     secure: U7MCSG3cjPF24Kgd8cLlolv9bYGF0tfXsnj2kN5DojhWDG48iF9kXI5o/v1dt+gouhKh8FivSb05UWkbXgLZnOUtPCjT1VQTLWBdRFb1yYaWgENac8WUYl3zJxqXt1jwVB0qsLr5ADvI8g/DSdIWony/y5SzhE0ATWGk4bVJViSeaMGrG5rBC0VccDdoIQzVifR/pdtMSl4evnXOEZOcWynFsJdQap/Pokl+8rn1dXqkpgVmF0jiDA6RfQq0RSstbNUImpWelaI3ojt0b0l3AQMsqpdb0pXcsLeiJIveplIDDszJPFWQqMvbk657n6emDdGN2YGK+zTw2XidS0OI8utUj2m847gp3Z+PXdvdBwlwM12SK3PSF3tAQOwlOJSOPoPPXNjLF9ZuZm7p7zsbZF4gQ6WM0RY8wRZpArG0/CAje+bImFQUqAHqF+VmGWyj2/ERYe7L5Zx8Pe3udH4HjfED+BQKH9GiOhFQHlqjNHW6KXhbhFvS9awjcTTPzq8NHVI3QDMx9LbapkK+BP3Wygu6VXGuf4kRs9ndz2rWuS79QmkHMVxSykVlL/zACregBEdRN3G8pShVxbzxgVCKIbgokMBz57B3PqRnDY0u8rS0lbCIrWAvVi+D+C4bNxdFt8Tg7uDkPZ7KroH8wMBKSZikcr3PfWuYfbvvMKi4VCE=